# Path to ffmpeg.exe
ffmpeg_executable=C:\bin\ffmpeg\bin\ffmpeg.exe

# Optional path to magick.exe. If omitted, cut-bot uses 'magick' from PATH.
# magick_executable=C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe

# Path to draw.io executable.
drawio_executable=C:\Program Files\draw.io\draw.io.exe